"""Add discount field

Revision ID: 8edfd5870909
Revises: c7116e417664
Create Date: 2025-03-29 15:10:07.444532

"""
import random
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app import crud
from random import randint

# revision identifiers, used by Alembic.
revision: str = '8edfd5870909'
down_revision: Union[str, None] = 'c7116e417664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('discount', sa.Float(), server_default='1.0', nullable=False))
    op.execute('COMMIT')
    # ### end Alembic commands ###
    sales = crud.sale.get_all()
    for sale in sales:
        discount = random.choices((1, (randint(70, 95) / 100), (randint(20, 70) / 100)), weights=(10, 5, 1))[0]
        sale.discount = discount
    crud.db_bulk_add(sales)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale', 'discount')
    # ### end Alembic commands ###
